### ISSUE TITLE
Functionality misparity for QuakeC

### ISSUE THREAD

**Issue by MotoLegacy** [nzp-team/quakespasm#12]
The following items are missing and need added in order to improve QuakeC parity between `QUAKESPASM` and `HANDHELD`:
* [x] `acheivement` builtin (`#79`)
* [x] `particle` builtin (`#48`)
* [x] `.float facingenemy` entity field
* [x] `.float bleed_out` entity field
* [x] `EF_RAYRED` and `EF_RAYGREEN` effects
* [x] `CMD_STRING` and `ParseClientCommand` system globals
* [x] `SoftRestart` system global
* [x] `.float iframetime` entity field
* [x] `getSoundLen` system global
* [x] `etos` system global
* [x] `movetoorigin` system global
* [x] `particle` system global
* [x] `centerprint<2-7>` system global (dummy probably)
* [x] `CloseWaypoint` system global
* [x] `tracebox` system global
* [x] `.string Weapon_Name` entity field (currently just in QC)

The following items function differently than `HANDHELD` platforms:
* [x] `.float zoom` entity field for ADS.
* [x] builtin `#79` is used for `logfrag` instead of `achievement`
* [x] `tokenize` is assigned `#130` instead of `#441`
* [x] `argv` is assigned `#131` instead of `#442`
* [x] `SVC_SMALLKICK` and `SVC_BIGKICK` occupy protocol byte spots `34` and `35`.
* [x] `PRINT_HIGH` is defined as `2` instead of `0`. (keep this!)

The following items should probably look into being removed as they're useless for us:
* [x] `.float dmg_take` and `.float dmg_save` entity fields

Side note, `.float renderGrayscale` should probably be removed from our QuakeC defs. We should just do all the health checks there, I think.
